eclipse-glsp/glsp-vscode-integration

example/workflow/scripts/download.ts
Hi,
when I ran `yarn install` and tried to run the workflow, the extension threw some errors complaining the server wasn't ready.
The issue was the download for the server failing (silently), because the target directory wasn't available, due to it not being checked into the VCS.
This PR aims to make the script fail verbosely and add the target folder to git, in order to make the setup work out of the box.
Note: I also thought about making the download script fail hard (e.g. `process.exit(1)`) but decided against it, because it is only affecting the example in case it fails.
=> Make install script work out of the box

package.json, vscode-integration-webview/package.json, vscode-integration/package.json, yarn.lock
Also add  update script to root package.json. The update script can be executed with `yarn upgrade:next`
Part of eclipse-glsp/glsp/issues/227
=> #227 Use concrete next version instead of tag

package.json, vscode-integration-webview/package.json, vscode-integration/package.json, yarn.lock
that occurred with eclipse-glsp/glsp/issues/227.
We still want to maintain a "yarn upgrade:next" script in all repositories.
Requires https://github.com/eclipse-glsp/glsp-client/pull/118
=> Revert #227

example/workflow/extension/package.json, example/workflow/extension/src/workflow-extension.ts, example/workflow/extension/src/workflow-glsp-diagram-editor-context.ts, package.json, vscode-integration-webview/src/extension-action-handler.ts, vscode-integration-webview/src/glsp-starter.ts, vscode-integration-webview/src/glsp-vscode-diagramserver.ts, vscode-integration/src/action/action.ts, vscode-integration/src/glsp-commands.ts, vscode-integration/src/glsp-diagram-editor-context.ts, vscode-integration/src/glsp-diagram-editor-provider.ts, vscode-integration/src/glsp-webview.ts, yarn.lock
Introduce `GLSPVscodeExtensionActionHandler` that provides the delegation/dispatching of local actions from the webview to the vsode extension. This enables the implementation of action handlers that require access  to the vscode API and/or node backend.
Also:
+ cleanup and centralize command registration into the `GLSPEditorContext` instead of the editor provider.
+ Add `registerActionHandlers()` to `GLSPEditorContext` method that enables the registration of additional extension action handlers in the user space
- Move `extensionPrefix` from constructor into abstract property
- Fix typos
=> #234 Improve action handling flow

packages/vscode-integration/src/action/index.ts, packages/vscode-integration/src/action/markers.ts, packages/vscode-integration/src/glsp-diagram-document.ts, packages/vscode-integration/src/glsp-diagram-editor-provider.ts, packages/vscode-integration/src/glsp-webview.ts
This PR addresses eclipse-glsp/glsp/issues/206 by implementing a basic feedback for GLSP markers in the VSCode problems view:
- Add `SetMarkersAction`.
- Let custom document handle `setMarkers` actions by setting diagnostics.
- Fix behaviour where messages from GLSP server were put into all webview message queues, instead of only those that are related to the server message.
part-of eclipse-glsp/glsp/issues/206.
=> Implement basic validation feedback in Problems view

Jenkinsfile, example/workflow/extension/package.json, example/workflow/extension/tsconfig.json, lerna.json, package.json, packages/vscode-integration-webview/README.md, packages/vscode-integration-webview/package.json, packages/vscode-integration/README.md, packages/vscode-integration/package.json, yarn.lock
- Add nightly next deployment for @eclipse-glsp/vscode-integration and @eclipse-glsp/vscodde-integration-webview
- Add missing readme to deployed packages
Also:
Update contributors metadata (eclipse-glsp/glsp/issues/246
Part of eclispse-glsp/glsp/issues/244
=> #244 Add nightly deployment for integration packages

.vscode/settings.json, package.json, packages/vscode-integration/src/glsp-vscode-connector.ts, yarn.lock
Update to latest glsp-config version to consume eclipse-glsp/glsp#405
(Update eslint-config to display formatting linting issues that get autofixed by prettier as warning)
(This is possible for all formatting linting rules except the "indent" rule. This rule has to be disabled. Prettier uses a dynamic indent size (e.g. spread objects (...) are formatted with two additional spaces, whereas es-lint only supports a static/fixed indent size. This causes unfixable warnings if the rule is activated. Prettier will still format and indent all lines correctly on save.
This means the developer should now get direct feedback in the editor again if there is a formatting issue like using " instead of ', multiple consecutive empty lines, missing semicolons etc.
Also:
Align yarn version range with Theia …
=> #377 Update to latest glsp-config version

packages/vscode-integration-webview/src/glsp-vscode-diagram-widget.ts
The `RequestTypeHints` action no longer supports a `diagramType` property. If a string is passed in the constructor is is used as `RequestId` instead. 
Since we dispatch the `RequestTypeHints` action as plain action notification (i.e. not with `actionDispatcher.request()`)  it will not be handled properly and the client never receives the `SetTypeHintsAction` result. 
Fixes eclipse-glsp/glsp/issues/516
=> #516 Fix invalid declaration `RequestTypeHintsAction` in diagram widget

example/workflow/extension/package.json, example/workflow/extension/scripts/download.ts, example/workflow/extension/src/server-config.json, example/workflow/extension/src/workflow-extension.ts, example/workflow/extension/tsconfig.json, package.json, packages/vscode-integration/src/quickstart-components/configuration-util.ts, yarn.lock
Upgrade yarn lock to consume latest glsp client version. (to consume https://github.com/eclipse-glsp/glsp-client/commit/4a5a0ee31d30e7a3ff8edf3fd5bc95065c841c1c)
Refactor server download script (analog to  https://github.com/eclipse-glsp/glsp-client/pull/194)
Use yarn resolutions to resolve sprotty version conflict (caused by upstream sprotty-vscode-webview)
Re-add missing registration of the `editorSelectedElementsAmount` context key
Fixes eclipse-glsp/glsp/issues/783
Fixes eclipse-glsp/glsp/issues/782
=> #783 Fix navigation & update to latest glsp client nighly

.github/workflows/codeql-analysis.yml, .gitignore, Jenkinsfile, README.md, example/workflow/extension/package.json, example/workflow/webview/package.json, package.json, packages/vscode-integration-webview/package.json, packages/vscode-integration/package.json, yarn.lock
- Update to lerna 6 and set node 14 as minimum engine version  https://github.com/eclipse-glsp/glsp/issues/676
https://github.com/eclipse-glsp/glsp/issues/680
- Update jenkins file to 
- ensure that we don't exhaust resource limits
- enable error reporting when master builds fails https://github.com/eclipse-glsp/glsp/issues/794
=> Update lerna and minimum node version

example/workflow/extension/src/workflow-extension.ts, packages/vscode-integration/README.md, packages/vscode-integration/src/quickstart-components/glsp-server-launcher.ts
All our GLSP server implementations are now capable of port autoassignment. The listening port is printed to STDOUT when the server is launched and has to be parsed by clients.
This patch adjusts the vscode integration to use the new port autoassignment.
Part of eclipse-glsp/glsp/issues/965
=> feat: adjust server startup to use autoassigned ports

.vscode/launch.json, package.json, packages/vscode-integration/src/glsp-vscode-connector.ts, packages/vscode-integration/src/quickstart-components/glsp-editor-provider.ts
Update the `onDidChangeCustomDocument` event emitter so that it is also possible to send events for dirty changes that have not been triggered by an edit/operation. Update `handleDirtyStateMethod` to  also emit a change event for reasons other than `operation`.
Also: Fix invalid source map paths of launch configs 
Fixes https://github.com/eclipse-glsp/glsp/issues/1006
=> GLSP-1006: Improve DirtyStateEventHandling

packages/vscode-integration/src/common/glsp-vscode-connector.ts
Sorry, while testing with a Java implementation of the progress reporting, I encountered a difference between Theia and VS Code:
VS Code expects increments relative to the previously reported progress. In GLSP UpdateProgressAction however we expect the full percentage in the action message. Thus, we need to make some adjustments before it over to the VS Code API.
=> Fix semantics of increment vs UpdateProgressAction

Jenkinsfile, packages/vscode-integration-webview/src/features/default/default-module.ts, packages/vscode-integration-webview/src/features/default/extension-action-handler.ts, packages/vscode-integration-webview/src/features/notification/notification-module.ts, packages/vscode-integration-webview/src/index.ts, packages/vscode-integration/src/common/glsp-vscode-connector.ts, packages/vscode-integration/src/common/quickstart-components/glsp-editor-provider.ts, packages/vscode-integration/src/common/types.ts, packages/vscode-integration/src/node/quickstart-components/glsp-socket-server-launcher.ts, packages/vscode-integration/src/node/quickstart-components/socket-glsp-vscode-server.ts, yarn.lock
Adapt codebase to client changes for eclipse-glsp/glsp/issues/1116
Part of eclipse-glsp/glsp/issues/1116
Ensure to use 127.0.0.1 over "localhost" as default to avoid ip v4/v6 issues
Fixes https://github.com/eclipse-glsp/glsp/issues/1100
Requires: https://github.com/eclipse-glsp/glsp-client/pull/288
=> GLSP-1116 Revise model loading

example/workflow/extension/package.json, example/workflow/extension/src/workflow-extension.ts, example/workflow/web-extension/package.json, example/workflow/web-extension/src/workflow-extension.ts, example/workflow/webview/package.json, lerna.json, packages/vscode-integration-webview/package.json, packages/vscode-integration-webview/src/features/copyPaste/copy-paste-module.ts, packages/vscode-integration-webview/src/features/default/default-module.ts, packages/vscode-integration-webview/src/features/default/extension-action-handler.ts, packages/vscode-integration-webview/src/features/default/vscode-glsp-modelsource.ts, packages/vscode-integration/package.json, packages/vscode-integration/src/common/glsp-vscode-connector.ts, packages/vscode-integration/src/common/quickstart-components/configuration-util.ts, packages/vscode-integration/src/common/quickstart-components/webview-endpoint.ts, yarn.lock
- Deprecate the concept of marking actions as locally dispatched by appending the `__localDispatch` property. This concept is a remainder of the 1.x API implementation and no longer necessary in 2.x. In addition, it conflicted with the default behavior of marking actions received from the server.
- Remove `ExtensionAction` bindings of `RequestClipboardDataAction` and `SetClipboardDataAction` in `vscodeCopyPasteModule`. These bindings where added on accident. As a consequence, related actions dispatched in the webview client where also forwarded back to the host extension where they were not handled.
Fixes https://github.com/eclipse-glsp/glsp/issues/1254
Test with different integration kinds. Diagram rendering should now work again.
https://github.com/eclipse-glsp/glsp/issues/1259
- [API] …
=> GLSP-1254 Fix client-server action forwarding

.github/PULL_REQUEST_TEMPLATE.md, example/workflow/extension/src/workflow-extension.ts, example/workflow/web-extension/src/workflow-extension.ts, example/workflow/webview/src/app.ts, package.json, packages/vscode-integration-webview/package.json, packages/vscode-integration-webview/src/features/copyPaste/copy-paste-module.ts, packages/vscode-integration-webview/src/features/default/default-module.ts, packages/vscode-integration-webview/src/features/default/extension-action-handler.ts, packages/vscode-integration-webview/src/features/default/vscode-glsp-modelsource.ts, packages/vscode-integration-webview/src/glsp-diagram-widget.ts, packages/vscode-integration-webview/src/glsp-starter.ts, packages/vscode-integration/package.json, packages/vscode-integration/src/browser/index.ts, packages/vscode-integration/src/browser/quickstart-components/browser-glsp-vscode-server.ts, packages/vscode-integration/src/browser/re-export.ts, packages/vscode-integration/src/common/client-actions.ts, packages/vscode-integration/src/common/glsp-vscode-connector.ts, packages/vscode-integration/src/common/index.ts, packages/vscode-integration/src/common/quickstart-components/configuration-util.ts, packages/vscode-integration/src/common/quickstart-components/glsp-editor-provider.ts, packages/vscode-integration/src/common/quickstart-components/webview-endpoint.ts, packages/vscode-integration/src/common/re-export.ts, packages/vscode-integration/src/common/types.ts, packages/vscode-integration/src/node/index.ts, packages/vscode-integration/src/node/quickstart-components/node-glsp-vscode-server.ts, packages/vscode-integration/src/node/re-export.ts, yarn.lock
- Updates to latest version of @eclipse-glsp/dev
- Add generate:index utility script
- Regenerate index files
- Fix codeActionsOnSave in vscode settings
- Refactor upgrade:next script
- Reformat code base with prettier
- Fix copyright headers (by running a full check with glsp checkHeaders . -t full)
Part of eclipse-glsp/glsp#1320
=> GLSP-1320: Update to latest glsp dev config

CHANGELOG.MD, example/workflow/extension/package.json, example/workflow/web-extension/package.json, example/workflow/workspace/example1.wf, package.json, packages/vscode-integration-webview/css/diagram.css, packages/vscode-integration-webview/css/features.css, packages/vscode-integration-webview/css/glsp-vscode.css, packages/vscode-integration-webview/css/tool-palette.css, packages/vscode-integration-webview/src/features/copyPaste/copy-paste-module.ts, packages/vscode-integration-webview/src/features/default/default-module.ts, packages/vscode-integration-webview/src/features/export/export-module.ts, packages/vscode-integration-webview/src/features/navigation/navigation-module.ts, packages/vscode-integration-webview/src/features/notification/notification-module.ts, packages/vscode-integration-webview/src/glsp-diagram-widget.ts, yarn.lock
- Update glsp next dependencies
- Use debuggable feature ids for all vscode feature modules
- Fix bug with `vscodeNavigationModule` that accidently reused the feature id from the navigation module instead of requiring it
- Adjust tool palette css
- Customize css for newly introduced features
- Ensure that `GLSPProjectionView` is properly rendered
- disable overflow of root div
- Add mouse listeners to diagram widget to only show projections bars when the diagram is focused
- Update example1.wf
- Fix title menu contributions. Vscode now requires an icon to render them properly
-   [ ] This PR should be mentioned in the changelog
-   [ ] This PR introduces a breaking change (if yes, provide more details below for the changelog and the migration guide)
=> Update to latest client changes

packages/vscode-integration-webview/css/diagram.css
This is a PR for reported issue #1431 - Visual Studio Code Integration theme support.
It just adds css overrides for sprotty text using vscode variables for better theme support.
When changing the theme in VSCode the text on nodes/edges remains black, this can be a bit of a problem for dark themes. Whit the change the text on diagram nodes/edges follows the setting of the VSCode theme and everything is visible.
=> add style for sprotty text using vscode variables for theme support

CHANGELOG.MD, Jenkinsfile, package.json, packages/vscode-integration-webview/src/webview-glsp-client.ts, packages/vscode-integration/src/common/quickstart-components/webview-endpoint.ts, yarn.lock
- Update to latest client version and adapt code base
- Drop support for node 16
- Update changelog
Part of: https://github.com/eclipse-glsp/glsp/issues/1456
Part of: https://github.com/eclipse-glsp/glsp/issues/1449
-   [ ] This PR should be mentioned in the changelog
-   [ ] This PR introduces a breaking change (if yes, provide more details below for the changelog and the migration guide)
=> GLSP-1449: Update inversify & drop node 16

packages/vscode-integration-webview/css/decoration.css
Resolves [#1497](https://github.com/eclipse-glsp/glsp/issues/1497) correcting the VSCode warning background border var referenced from "borderd" to "border"
While viewing a diagram in a VSCode webview with warning type validations, notice the warning decorator is black, not yellow. This change resolves this, and rightly sets it to the VSCode warning border yellow. 
-   [x] This PR should be mentioned in the changelog
-   [ ] This PR introduces a breaking change (if yes, provide more details below for the changelog and the migration guide)
=> GLSP-1497: Correct glsp warning foreground var

packages/vscode-integration/src/common/glsp-vscode-connector.ts, packages/vscode-integration/src/common/types.ts
- Allow to configure the vscode-messenger instance used by the GLSPVSCodeConnector via consturctor options.
- Set the `ignoreHiddenViews` options to false in the default messenger instance
Fixes https://github.com/eclipse-glsp/glsp/issues/1455
-   [ ] This PR should be mentioned in the changelog
-   [ ] This PR introduces a breaking change (if yes, provide more details below for the changelog and the migration guide)
=> GLSP-1455: Allow configuration of messenger instance
